# Data source
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api?useSSL=true
    username: userapi
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    autoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
# JWT
api:
  security:
    token:
      secret: ${JWT_SECRET:123456}